//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLMultimarcas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string NomeFuncionario { get; set; }
        [DisplayName("Usuário")]
        [Required(ErrorMessage = "É necessário informar o usuário.")]
        public string LoginFuncionario { get; set; }
        [DisplayName("Senha")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "É necessário informar a senha.")]
        public string SenhaFuncionario { get; set; }
        public string EmailFuncionario { get; set; }
        public int AdicionarFuncionario { get; set; }
        public int AdicionarVeiculo { get; set; }
        public int EditarFuncionario { get; set; }
        public int EditarVeiculo { get; set; }
        public int ExcluirFuncionario { get; set; }
        public int ExcluirVeiculo { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
