//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLMultimarcas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string NomeFuncionario { get; set; }
        public string LoginFuncionario { get; set; }
        public string SenhaFuncionario { get; set; }
        public string EmailFuncionario { get; set; }
        public int AdicionarFuncionario { get; set; }
        public int AdicionarVeiculo { get; set; }
        public int EditarFuncionario { get; set; }
        public int EditarVeiculo { get; set; }
        public int ExcluirFuncionario { get; set; }
        public int ExcluirVeiculo { get; set; }
    }
}
