//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLMultimarcas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int IdVeiculo { get; set; }
        public string Placa { get; set; }
        public int IdModelo { get; set; }
        public int IdMarca { get; set; }
        public int IdClasse { get; set; }
        public int IdPotencia { get; set; }
        public int IdCombustivel { get; set; }
        public int IdCor { get; set; }
        public int IdCondicao { get; set; }
        public double Valor { get; set; }
    
        public virtual Classe Classe { get; set; }
        public virtual Combustivel Combustivel { get; set; }
        public virtual Condicao Condicao { get; set; }
        public virtual Cor Cor { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Potencia Potencia { get; set; }
    }
}
